branch: master

verifyConditions:
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
  - '@semantic-release/git'
  - path: '@semantic-release/gitlab'
    gitlabUrl: 'https://gitlab.com'

prepare:
  - path: '@semantic-release/changelog'
    changelogFile: 'CHANGELOG.md'
  - '@semantic-release/npm'
  - path: '@semantic-release/git'
    assets:
      - package.json
      - CHANGELOG.md

publish:
  - '@semantic-release/npm'
  - path: '@semantic-release/gitlab'
    gitlabUrl: 'https://gitlab.com'

success: []

fail: []
